### PR TITLE
[REMOVE]Remove redundant static policy test cases

### PR DESCRIPTION
**Pull request by pablitoergosum**
Remove redundant test cases

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@pablitoergosum Did you check the test coverage before and after the remove?

**Comment by pablitoergosum** [comment]
I did it just now, it dropped slightly - from ``coverage: 81.1% of statements`` before the change to ``coverage: 80.9% of statements
``.  Thanks for pointing this out, I will investigate it.

**Comment by k-wiatrzyk** [comment]
How does coverage look like after the update?

**Comment by pablitoergosum** [comment]
It didn't change - stays on 81.1% level.

**Comment by cynepco3hahue** [comment]
@pablitoergosum If you want to have it under the k8s memory manager PR, you should create your PR vs feature-memory-manager-working branch.

**Pull request closed without merging**
